let coms=[];  
import MeasureArea from '../views/maps/components/Common/MeasureArea/index.vue';
coms.push(MeasureArea);
import SplitScreen from '../views/maps/components/Common/SplitScreen/index.vue';
coms.push(SplitScreen);
import SplitScreenPop from '../views/maps/components/Common/SplitScreen/SplitScreenPop';
coms.push(SplitScreenPop);
import TransparentTerrain from '../views/maps/components/Common/TransparentTerrain/index.vue';
coms.push(TransparentTerrain);
import TransparentTerrainPop from '../views/maps/components/Common/TransparentTerrain/TransparentTerrainPop';
coms.push(TransparentTerrainPop);
import CoordinateLabel from '../views/maps/components/Common/CoordinateLabel/index.vue';
coms.push(CoordinateLabel);
import CoordinateLabelPop from '../views/maps/components/Common/CoordinateLabel/CoordinateLabelPop';
coms.push(CoordinateLabelPop);
import AnimationNavigation from '../views/maps/components/Common/AnimationNavigation/index.vue';
coms.push(AnimationNavigation);
import AnimationNavigationPop from '../views/maps/components/Common/AnimationNavigation/AnimationNavigationPop';
coms.push(AnimationNavigationPop);
import CoordinatePosition from '../views/maps/components/Common/CoordinatePosition/index.vue';
coms.push(CoordinatePosition);
import CoordinatePositionPop from '../views/maps/components/Common/CoordinatePosition/CoordinatePositionPop';
coms.push(CoordinatePositionPop);
import ElementHidden from '../views/maps/components/Common/ElementHidden/index.vue';
coms.push(ElementHidden);
import LineNavigation from '../views/maps/components/Common/LineNavigation/index.vue';
coms.push(LineNavigation);
import LineNavigationPop from '../views/maps/components/Common/LineNavigation/LineNavigationPop';
coms.push(LineNavigationPop);
import MeasureLine from '../views/maps/components/Common/MeasureLine/index.vue';
coms.push(MeasureLine);
import MeasureSpace from '../views/maps/components/Common/MeasureSpace/index.vue';
coms.push(MeasureSpace);
import TextLabel from '../views/maps/components/Common/TextLabel/index.vue';
coms.push(TextLabel);
import TextLabelPop from '../views/maps/components/Common/TextLabel/TextLabelPop';
coms.push(TextLabelPop);
import TransparentGround from '../views/maps/components/Common/TransparentGround/index.vue';
coms.push(TransparentGround);
import TransparentGroundPop from '../views/maps/components/Common/TransparentGround/TransparentGroundPop';
coms.push(TransparentGroundPop);
import ViewMode from '../views/maps/components/Common/ViewMode/index.vue';
coms.push(ViewMode);
import TimelineDataContrast from '../views/maps/components/Common/TimelineDataContrast/index.vue';
coms.push(TimelineDataContrast);
import TimelineDataContrastPop from '../views/maps/components/Common/TimelineDataContrast/TimelineDataContrastPop';
coms.push(TimelineDataContrastPop);
import DrawGraph from '../views/maps/components/Common/DrawGraph/index.vue';
coms.push(DrawGraph);
import DrawPLS from '../views/maps/components/Common/DrawGraph/DrawPLS';
coms.push(DrawPLS);
import DrawGeometric from '../views/maps/components/Common/DrawGeometric/index.vue';
coms.push(DrawGeometric);
import GeometricPop from '../views/maps/components/Common/DrawGeometric/GeometricPop';
coms.push(GeometricPop);
import Fire from '../views/maps/components/SceneEffects/Fire/index.vue';
coms.push(Fire);
import FirePop from '../views/maps/components/SceneEffects/Fire/FirePop';
coms.push(FirePop);
import FlyLines from '../views/maps/components/SceneEffects/FlyLines/index.vue';
coms.push(FlyLines);
import FountainEffect from '../views/maps/components/SceneEffects/FountainEffect/index.vue';
coms.push(FountainEffect);
import FountainEffectPop from '../views/maps/components/SceneEffects/FountainEffect/FountainEffectPop';
coms.push(FountainEffectPop);
import IotPerception from '../views/maps/components/SceneEffects/IotPerception/index.vue';
coms.push(IotPerception);
import IotPerceptionPop from '../views/maps/components/SceneEffects/IotPerception/IotPerceptionPop';
coms.push(IotPerceptionPop);
import MigrationMap from '../views/maps/components/SceneEffects/MigrationMap/index.vue';
coms.push(MigrationMap);
import Rain from '../views/maps/components/SceneEffects/Rain/index.vue';
coms.push(Rain);
import RollerCompare from '../views/maps/components/SceneEffects/RollerCompare/index.vue';
coms.push(RollerCompare);
import RollerComparePop from '../views/maps/components/SceneEffects/RollerCompare/RollerComparePop';
coms.push(RollerComparePop);
import RollerModelCompare from '../views/maps/components/SceneEffects/RollerModelCompare/index.vue';
coms.push(RollerModelCompare);
import RollerModelComparePop from '../views/maps/components/SceneEffects/RollerModelCompare/RollerModelComparePop';
coms.push(RollerModelComparePop);
import ScanLines from '../views/maps/components/SceneEffects/ScanLines/index.vue';
coms.push(ScanLines);
import ScanLinesPop from '../views/maps/components/SceneEffects/ScanLines/ScanLinesPop';
coms.push(ScanLinesPop);
import Snow from '../views/maps/components/SceneEffects/Snow/index.vue';
coms.push(Snow);
import WindFarm from '../views/maps/components/SceneEffects/WindFarm/index.vue';
coms.push(WindFarm);
import WindFarmPop from '../views/maps/components/SceneEffects/WindFarm/WindFarmPop';
coms.push(WindFarmPop);
import Sensors from '../views/maps/components/SceneEffects/Sensors/index.vue';
coms.push(Sensors);
import sensorsPop from '../views/maps/components/SceneEffects/Sensors/sensorsPop';
coms.push(sensorsPop);
import Bookmarks from '../views/maps/components/Basic/Bookmarks/index.vue';
coms.push(Bookmarks);
import BookmarksPop from '../views/maps/components/Basic/Bookmarks/BookmarksPop';
coms.push(BookmarksPop);
import LayerTree from '../views/maps/components/Basic/LayerTree/index.vue';
coms.push(LayerTree);
import LayerTreePop from '../views/maps/components/Basic/LayerTree/LayerTreePop';
coms.push(LayerTreePop);
import ManagerApproval from '../views/maps/components/Basic/ManagerApproval/index.vue';
coms.push(ManagerApproval);
import ManagerApprovalPop from '../views/maps/components/Basic/ManagerApproval/ManagerApprovalPop';
coms.push(ManagerApprovalPop);
import QueryPick from '../views/maps/components/Basic/QueryPick/index.vue';
coms.push(QueryPick);
import QueryPickPop from '../views/maps/components/Basic/QueryPick/QueryPickPop';
coms.push(QueryPickPop);
import ScenePlottingPop from '../views/maps/components/Basic/ScenePlotting/ScenePlottingPop';
coms.push(ScenePlottingPop);
import BoxClip from '../views/maps/components/SpatialAnalysis/BoxClip/index.vue';
coms.push(BoxClip);
import BoxClipPop from '../views/maps/components/SpatialAnalysis/BoxClip/BoxClipPop';
coms.push(BoxClipPop);
import BuildingServicesScope from '../views/maps/components/SpatialAnalysis/BuildingServicesScope/index.vue';
coms.push(BuildingServicesScope);
import BuildingServicesScopePop from '../views/maps/components/SpatialAnalysis/BuildingServicesScope/BuildingServicesScopePop';
coms.push(BuildingServicesScopePop);
import DrawerEffect from '../views/maps/components/SpatialAnalysis/DrawerEffect/index.vue';
coms.push(DrawerEffect);
import FacadeAnalysis from '../views/maps/components/SpatialAnalysis/FacadeAnalysis/index.vue';
coms.push(FacadeAnalysis);
import FacadeAnalysisPop from '../views/maps/components/SpatialAnalysis/FacadeAnalysis/FacadeAnalysisPop';
coms.push(FacadeAnalysisPop);
import InundationAnalysis from '../views/maps/components/SpatialAnalysis/InundationAnalysis/index.vue';
coms.push(InundationAnalysis);
import InundationAnalysisPop from '../views/maps/components/SpatialAnalysis/InundationAnalysis/InundationAnalysisPop';
coms.push(InundationAnalysisPop);
import LayerAnimation from '../views/maps/components/SpatialAnalysis/LayerAnimation/index.vue';
coms.push(LayerAnimation);
import MeasureSpear from '../views/maps/components/SpatialAnalysis/MeasureSpear/index.vue';
coms.push(MeasureSpear);
import ModelCut from '../views/maps/components/SpatialAnalysis/ModelCut/index.vue';
coms.push(ModelCut);
import ModelCutPop from '../views/maps/components/SpatialAnalysis/ModelCut/ModelCutPop';
coms.push(ModelCutPop);
import OpennessAnalysis from '../views/maps/components/SpatialAnalysis/OpennessAnalysis/index.vue';
coms.push(OpennessAnalysis);
import OpennessAnalysisPop from '../views/maps/components/SpatialAnalysis/OpennessAnalysis/OpennessAnalysisPop';
coms.push(OpennessAnalysisPop);
import PolygonClip from '../views/maps/components/SpatialAnalysis/PolygonClip/index.vue';
coms.push(PolygonClip);
import PolygonClipPop from '../views/maps/components/SpatialAnalysis/PolygonClip/PolygonClipPop';
coms.push(PolygonClipPop);
import ProfileAnalysis from '../views/maps/components/SpatialAnalysis/ProfileAnalysis/index.vue';
coms.push(ProfileAnalysis);
import ProfileAnalysisPop from '../views/maps/components/SpatialAnalysis/ProfileAnalysis/ProfileAnalysisPop';
coms.push(ProfileAnalysisPop);
import TerrainExcavate from '../views/maps/components/SpatialAnalysis/TerrainExcavate/index.vue';
coms.push(TerrainExcavate);
import TerrainExcavatePop from '../views/maps/components/SpatialAnalysis/TerrainExcavate/TerrainExcavatePop';
coms.push(TerrainExcavatePop);
import TerrainFlatten from '../views/maps/components/SpatialAnalysis/TerrainFlatten/index.vue';
coms.push(TerrainFlatten);
import TerrainInundation from '../views/maps/components/SpatialAnalysis/TerrainInundation/index.vue';
coms.push(TerrainInundation);
import TerrainInundationPop from '../views/maps/components/SpatialAnalysis/TerrainInundation/TerrainInundationPop';
coms.push(TerrainInundationPop);
import TerrainRelief from '../views/maps/components/SpatialAnalysis/TerrainRelief/index.vue';
coms.push(TerrainRelief);
import TerrainReliefPop from '../views/maps/components/SpatialAnalysis/TerrainRelief/TerrainReliefPop';
coms.push(TerrainReliefPop);
import VideoPut from '../views/maps/components/SpatialAnalysis/VideoPut/index.vue';
coms.push(VideoPut);
import VideoPutPop from '../views/maps/components/SpatialAnalysis/VideoPut/VideoPutPop';
coms.push(VideoPutPop);
import VisualRangeAnalysis from '../views/maps/components/SpatialAnalysis/VisualRangeAnalysis/index.vue';
coms.push(VisualRangeAnalysis);
import VisualRangeAnalysisPop from '../views/maps/components/SpatialAnalysis/VisualRangeAnalysis/VisualRangeAnalysisPop';
coms.push(VisualRangeAnalysisPop);
import AttributeHidden from '../views/maps/components/QueryStatistics/AttributeHidden/index.vue';
coms.push(AttributeHidden);
import AttributeHiddenPop from '../views/maps/components/QueryStatistics/AttributeHidden/AttributeHiddenPop';
coms.push(AttributeHiddenPop);
import QueryAttribute from '../views/maps/components/QueryStatistics/QueryAttribute/index.vue';
coms.push(QueryAttribute);
import QueryAttributePop from '../views/maps/components/QueryStatistics/QueryAttribute/QueryAttributePop';
coms.push(QueryAttributePop);
import QueryComprehensive from '../views/maps/components/QueryStatistics/QueryComprehensive/index.vue';
coms.push(QueryComprehensive);
import QueryComprehensivePop from '../views/maps/components/QueryStatistics/QueryComprehensive/QueryComprehensivePop';
coms.push(QueryComprehensivePop);
import QueryPlaceName from '../views/maps/components/QueryStatistics/QueryPlaceName/index.vue';
coms.push(QueryPlaceName);
import QueryPlaceNamePop from '../views/maps/components/QueryStatistics/QueryPlaceName/QueryPlaceNamePop';
coms.push(QueryPlaceNamePop);
import QueryRoad from '../views/maps/components/QueryStatistics/QueryRoad/index.vue';
coms.push(QueryRoad);
import QueryRoadPop from '../views/maps/components/QueryStatistics/QueryRoad/QueryRoadPop';
coms.push(QueryRoadPop);
import QuerySpatial from '../views/maps/components/QueryStatistics/QuerySpatial/index.vue';
coms.push(QuerySpatial);
import QuerySpatialPop from '../views/maps/components/QueryStatistics/QuerySpatial/QuerySpatialPop';
coms.push(QuerySpatialPop);
import QueryStatistic from '../views/maps/components/QueryStatistics/QueryStatistic/index.vue';
coms.push(QueryStatistic);
import QueryStatisticPop from '../views/maps/components/QueryStatistics/QueryStatistic/QueryStatisticPop';
coms.push(QueryStatisticPop);
import SearchObject from '../views/maps/components/QueryStatistics/SearchObject/index.vue';
coms.push(SearchObject);
import SearchObjectPop from '../views/maps/components/QueryStatistics/SearchObject/SearchObjectPop';
coms.push(SearchObjectPop);
import SearchVideo from '../views/maps/components/QueryStatistics/SearchVideo/index.vue';
coms.push(SearchVideo);
import SearchVideoPop from '../views/maps/components/QueryStatistics/SearchVideo/SearchVideoPop';
coms.push(SearchVideoPop);
import SpaceHidden from '../views/maps/components/QueryStatistics/SpaceHidden/index.vue';
coms.push(SpaceHidden);
import SpaceHiddenPop from '../views/maps/components/QueryStatistics/SpaceHidden/SpaceHiddenPop';
coms.push(SpaceHiddenPop);
import SurveillanceVideo from '../views/maps/components/QueryStatistics/SurveillanceVideo/index.vue';
coms.push(SurveillanceVideo);
import SurveillanceVideoPop from '../views/maps/components/QueryStatistics/SurveillanceVideo/SurveillanceVideoPop';
coms.push(SurveillanceVideoPop);
import BurstAnalysis from '../views/maps/components/PipeManager/BurstAnalysis/index.vue';
coms.push(BurstAnalysis);
import BurstAnalysisPop from '../views/maps/components/PipeManager/BurstAnalysis/BurstPop';
coms.push(BurstAnalysisPop);
import ConnectAnalysis from '../views/maps/components/PipeManager/ConnectAnalysis/index.vue';
coms.push(ConnectAnalysis);
import ConnectAnalysisPop from '../views/maps/components/PipeManager/ConnectAnalysis/ConnectAnalysisPop';
coms.push(ConnectAnalysisPop);
import CoverageAnalysis from '../views/maps/components/PipeManager/CoverageAnalysis/index.vue';
coms.push(CoverageAnalysis);
import CoverageAnalysisPop from '../views/maps/components/PipeManager/CoverageAnalysis/CoverageAnalysisPop';
coms.push(CoverageAnalysisPop);
import DistanceAnalysis from '../views/maps/components/PipeManager/DistanceAnalysis/index.vue';
coms.push(DistanceAnalysis);
import DistanceAnalysisPop from '../views/maps/components/PipeManager/DistanceAnalysis/DistancePop';
coms.push(DistanceAnalysisPop);
import ExcavationAnalysis from '../views/maps/components/PipeManager/ExcavationAnalysis/index.vue';
coms.push(ExcavationAnalysis);
import ExcavationAnalysisPop from '../views/maps/components/PipeManager/ExcavationAnalysis/ExcatatePop';
coms.push(ExcavationAnalysisPop);
import FlowDirectionAnalysis from '../views/maps/components/PipeManager/FlowDirectionAnalysis/index.vue';
coms.push(FlowDirectionAnalysis);
import FlowDirectionAnalysisPop from '../views/maps/components/PipeManager/FlowDirectionAnalysis/FlowDirectionAnalysis';
coms.push(FlowDirectionAnalysisPop);
import HydrantSearch from '../views/maps/components/PipeManager/HydrantSearch/index.vue';
coms.push(HydrantSearch);
import HydrantSearchPop from '../views/maps/components/PipeManager/HydrantSearch/HydrantSearchPop';
coms.push(HydrantSearchPop);
import LabelTool from '../views/maps/components/PipeManager/LabelTool/index.vue';
coms.push(LabelTool);
import IconLabelPop from '../views/maps/components/PipeManager/LabelTool/IconLabelPop';
coms.push(IconLabelPop);
import DeleteLabel from '../views/maps/components/PipeManager/DeleteLabel/index.vue';
coms.push(DeleteLabel);
import ManagerPanelPop from '../views/maps/components/PipeManager/ManagerPanel/ManagerPanel';
coms.push(ManagerPanelPop);
import PipeCollision from '../views/maps/components/PipeManager/PipeCollision/index.vue';
coms.push(PipeCollision);
import PipeCollisionPop from '../views/maps/components/PipeManager/PipeCollision/CollisionPop';
coms.push(PipeCollisionPop);
import PipeContionQuery from '../views/maps/components/PipeManager/PipeContionQuery/index.vue';
coms.push(PipeContionQuery);
import DiameterQueryPop from '../views/maps/components/PipeManager/PipeContionQuery/DiameterQueryPop';
coms.push(DiameterQueryPop);
import FeildQueryPop from '../views/maps/components/PipeManager/PipeContionQuery/FeildQueryPop';
coms.push(FeildQueryPop);
import MaterialQueryPop from '../views/maps/components/PipeManager/PipeContionQuery/MaterialQueryPop';
coms.push(MaterialQueryPop);
import PropertyQueryPop from '../views/maps/components/PipeManager/PipeContionQuery/PropertyQueryPop';
coms.push(PropertyQueryPop);
import PipeLegend from '../views/maps/components/PipeManager/PipeLegend/index.vue';
coms.push(PipeLegend);
import PipeLegendPop from '../views/maps/components/PipeManager/PipeLegend/PipeLegendPop';
coms.push(PipeLegendPop);
import PipeMark from '../views/maps/components/PipeManager/PipeMark/index.vue';
coms.push(PipeMark);
import PipeMarkPop from '../views/maps/components/PipeManager/PipeMark/PipeMarkPop';
coms.push(PipeMarkPop);
import PipeQuery from '../views/maps/components/PipeManager/PipeQuery/index.vue';
coms.push(PipeQuery);
import PipeQueryPop from '../views/maps/components/PipeManager/PipeQuery/QueryPop';
coms.push(PipeQueryPop);
import PipeStatistics from '../views/maps/components/PipeManager/PipeStatistics/index.vue';
coms.push(PipeStatistics);
import DepthSectPop from '../views/maps/components/PipeManager/PipeStatistics/DepthSectPop';
coms.push(DepthSectPop);
import DiameterPop from '../views/maps/components/PipeManager/PipeStatistics/DiameterPop';
coms.push(DiameterPop);
import DiameterSectPop from '../views/maps/components/PipeManager/PipeStatistics/DiameterSectPop';
coms.push(DiameterSectPop);
import MaterialPop from '../views/maps/components/PipeManager/PipeStatistics/MaterialPop';
coms.push(MaterialPop);
import PropertyPop from '../views/maps/components/PipeManager/PipeStatistics/PropertyPop';
coms.push(PropertyPop);
import SectionalAnalysis from '../views/maps/components/PipeManager/SectionalAnalysis/index.vue';
coms.push(SectionalAnalysis);
import TrackingAnalysis from '../views/maps/components/PipeManager/TrackingAnalysis/index.vue';
coms.push(TrackingAnalysis);
import TrackingAnalysisPop from '../views/maps/components/PipeManager/TrackingAnalysis/TrackingAnalysis';
coms.push(TrackingAnalysisPop);
const install = function (Vue) { 
coms.forEach((com) => { 
Vue.component(com.name, com);
});
};   
 export default  install ;