CREATE TABLE
IF
	NOT EXISTS stargis_geodata (
		realId INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '唯一标识',
		projectName VARCHAR ( 255 ) NOT NULL COMMENT '项目名称',
		moduleName VARCHAR ( 255 ) COMMENT '模块名称',
		miniModuleName VARCHAR ( 255 ) COMMENT '子模块名称',
		dataName VARCHAR ( 255 ) COMMENT '数据名称',
		properties TEXT COMMENT '属性',
		geometry TEXT COMMENT '几何',
		id INT COMMENT '要素id',
		crs VARCHAR ( 255 ) COMMENT 'crs信息',
		creator VARCHAR ( 64 ) COMMENT '创建人',
		updater VARCHAR ( 64 ) COMMENT '修改人',
		creation_Time datetime COMMENT '创建时间',
		modification_Time datetime COMMENT '修改时间' 
	) COMMENT 'geojson数据';
CREATE TABLE
IF
	NOT EXISTS stargis_customform (
		realId INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '唯一标识',
		projectName VARCHAR ( 255 ) NOT NULL COMMENT '项目名称',
		moduleName VARCHAR ( 255 ) COMMENT '模块名称',
		miniModuleName VARCHAR ( 255 ) COMMENT '子模块名称',
		dataName VARCHAR ( 255 ) COMMENT '数据名称',
		num1 DOUBLE COMMENT '数值1',
		num2 DOUBLE COMMENT '数值2',
		num3 DOUBLE COMMENT '数值3',
		num4 DOUBLE COMMENT '数值4',
		num5 DOUBLE COMMENT '数值5',
		num6 DOUBLE COMMENT '数值6',
		num7 DOUBLE COMMENT '数值7',
		num8 DOUBLE COMMENT '数值8',
		num9 DOUBLE COMMENT '数值9',
		num10 DOUBLE COMMENT '数值10',
		num11 DOUBLE COMMENT '数值11',
		num12 DOUBLE COMMENT '数值12',
		num13 DOUBLE COMMENT '数值13',
		num14 DOUBLE COMMENT '数值14',
		num15 DOUBLE COMMENT '数值15',
		num16 DOUBLE COMMENT '数值16',
		num17 DOUBLE COMMENT '数值17',
		num18 DOUBLE COMMENT '数值18',
		num19 DOUBLE COMMENT '数值19',
		num20 DOUBLE COMMENT '数值20',
		str1 TEXT COMMENT '字符串1',
		str2 TEXT COMMENT '字符串2',
		str3 TEXT COMMENT '字符串3',
		str4 TEXT COMMENT '字符串4',
		str5 TEXT COMMENT '字符串5',
		str6 TEXT COMMENT '字符串6',
		str7 TEXT COMMENT '字符串7',
		str8 TEXT COMMENT '字符串8',
		str9 TEXT COMMENT '字符串9',
		str10 TEXT COMMENT '字符串10',
		str11 TEXT COMMENT '字符串11',
		str12 TEXT COMMENT '字符串12',
		str13 TEXT COMMENT '字符串13',
		str14 TEXT COMMENT '字符串14',
		str15 TEXT COMMENT '字符串15',
		str16 TEXT COMMENT '字符串16',
		str17 TEXT COMMENT '字符串17',
		str18 TEXT COMMENT '字符串18',
		str19 TEXT COMMENT '字符串19',
		str20 TEXT COMMENT '字符串20',
		time1 DATETIME COMMENT '时间1',
		time2 DATETIME COMMENT '时间2',
		time3 DATETIME COMMENT '时间3',
		time4 DATETIME COMMENT '时间4',
		time5 DATETIME COMMENT '时间5',
		time6 DATETIME COMMENT '时间6',
		time7 DATETIME COMMENT '时间7',
		time8 DATETIME COMMENT '时间8',
		time9 DATETIME COMMENT '时间9',
		time10 DATETIME COMMENT '时间10',
		creator VARCHAR ( 64 ) COMMENT '创建人',
		updater VARCHAR ( 64 ) COMMENT '修改人',
		creation_Time datetime COMMENT '创建时间',
		modification_Time datetime COMMENT '修改时间' 
	) COMMENT '自定义表单';
CREATE TABLE
IF
	NOT EXISTS stargis_filedata (
		realId INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '唯一标识',
		projectName VARCHAR ( 255 ) NOT NULL COMMENT '项目名称',
		moduleName VARCHAR ( 255 ) COMMENT '模块名称',
		miniModuleName VARCHAR ( 255 ) COMMENT '子模块名称',
		typeName VARCHAR ( 255 ) COMMENT '类别名称',
		fileName TEXT COMMENT '文件名',
		addTime DATETIME COMMENT '入库时间',
		creator VARCHAR ( 64 ) COMMENT '创建人',
		updater VARCHAR ( 64 ) COMMENT '修改人',
		creation_Time datetime COMMENT '创建时间',
	modification_Time datetime COMMENT '修改时间' 
	) COMMENT '文件数据';